### ISSUE TITLE
openshift_register_nodes role doesn't inherit common vars from openshift_common

### ISSUE THREAD

**Issue by thoraxe** [detiber/openshift-ansible#28]

**Comment by detiber** [comment]
@thoraxe is there a specific issue you see related to this? There shouldn't be any dependency on anything in openshift_common for openshift_register_nodes.

All variable references to openshift.common.\* are actually being supplied from the openshift_facts module.

**Comment by thoraxe** [comment]
register_nodes references a variable that already exists in common, but isn't visible. So you end up duplicating it. 

It makes it seem that common is not so common. 

For an Ansible newb like myself it took a lot of messing around to figure out what was going on. Just look at my ugly pr :-)

**Comment by detiber** [comment]
@thoraxe ah, gotcha.  I'm hesitant to modify this behavior currently, since openshift_register_nodes is a bit of an oddball (in that it was initially designed to run on the nodes and then was modified to run on the master instead), also once the upstream node self-registration is in place openshift_register_nodes will no longer be needed (whether that is in place for GA or not is yet to be seen though).

**Comment by thoraxe** [comment]
OK, if it's just temporary I guess that's not really a problem then.
