### ISSUE TITLE
master-only installation fails

### ISSUE THREAD

**Issue by thoraxe** [detiber/openshift-ansible#29]
I've seen this a couple of times i think, and I just wanted to confirm whether or not it was still an issue.

If the master is not also specified as being a node, the installation fails. EG you cannot seem to create a "master-only" host.

**Comment by detiber** [comment]
@thoraxe I would expect this if running the playbooks/byo/config.yml playbook, since I'm probably not validating that there are node hosts before trying to include the node config playbook.

Running the playbooks/byo/openshift-master/config.yml doesn't include any references to variables that would require a node to be present.

**Comment by thoraxe** [comment]
But if you have both nodes and masters defined, you then have to run the installer twice (or so it seems). Once against the master playbook and then against the node playbook?

**Comment by detiber** [comment]
@thoraxe correct, I'll keep this issue open, and attempt to take a look at fixing up the playbooks/byo/config.yml to not bomb out in that way (after tackling the templating of the configs and any other issues that come up), The error that is given is ugly, but it occurs after the master is configured (the node configuration happens after the master configuration), so it really is only a cosmetic error.
